### ISSUE TITLE
Capitulo 6 - io is not defined

### ISSUE THREAD

**Issue by viniciusvsb** [caio-ribeiro-pereira/livro-nodejs#14]
Fala caio, seguindo o exemplo inicial do socket.io na pagina 73-74. Obtenho sempre 404 sobre a chamada `<script src="/socket.io/socket.io.js"></script>` e consequentemente a mensagem  "io is not defined". Em uma pesquisa rápida vi algumas sugestões para adicionar localhost:3000 na chamada do js, mas também não funcionou. O meu app.js seguiu a evolução que o livro propôs. Segue abaixo:

``` javascript
var express = require('express')
, load = require('express-load')
, bodyParser = require('body-parser')
, cookieParser = require('cookie-parser')
, expressSession = require('express-session')
, methodOverride = require('method-override')
, error = require('./middlewares/error')
, app = express()
, server = require('http').Server(app)
, io = require('socket.io')(server);

app.set('views', __dirname + '/views');
app.set('view engine', 'ejs');
app.use(cookieParser('ntalk'));
app.use(expressSession());
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({extended: true}));
app.use(methodOverride('_method'));
app.use(express.static(__dirname + '/public'));

load('models')
.then('controllers')
.then('routes')
.into(app);

io.sockets.on('connection', function(client){
    client.on('send-server', function(data){
        var msg = "<b>" + data.nome + ": </b>" + data.msg + "<br>";
        client.emit('send-client', msg);
        client.broadcast.emit('send-client', msg);
    });
});

app.use(error.notFound);
app.use(error.serverError);

app.listen(3000, function(){
  console.log("Ntalk no ar.");
});
```

Abs.

**Comment by egamorim** [comment]
Boa tarde Caio.

Estou com o mesmo problema. Pode me ajudar por favor?

**Comment by caio-ribeiro-pereira** [comment]
@egamorim qual seria seu problema em específico? pois se for o mesmo problema a solução já se encontra no inicio dessa issue.

**Comment by egamorim** [comment]
É o mesmo problema sim, e também no client.
Tentei como no livro : <script src="/socket.io/socket.io.js"></script>
e depois pesquisei um pouco na net e tentei : 
<script src="https://cdn.socket.io/socket.io-1.2.0.js"></script>
Mas ele continua retornando 404 como no caso do viniciusvsb.

**Comment by caio-ribeiro-pereira** [comment]
Se não esta funcionando direito carregar o socket.io.js local, então carregue o script pelo CDN do socket.io: 

`<script src="https://cdn.socket.io/socket.io-1.3.5.js"></script>`

**Comment by egamorim** [comment]
Fiz esse teste e no console do navegador apareceu esse o seguinte erro: 
GET http://localhost:3000/socket.io/?EIO=3&transport=polling&t=1432848103170-0 404 (Not Found)17.Request.create @ socket.io-1.3.5.js:2Request @ socket.io-1.3.5.js:217.XHR.request @ socket.io-1.3.5.js:217.XHR.doPoll @ socket.io-1.3.5.js:218.Polling.poll @ socket.io-1.3.5.js:218.Polling.doOpen @ socket.io-1.3.5.js:214.Transport.open @ socket.io-1.3.5.js:113.Socket.open @ socket.io-1.3.5.js:1Socket @ socket.io-1.3.5.js:1Socket @ socket.io-1.3.5.js:13.Manager.open.Manager.connect @ socket.io-1.3.5.js:1Manager @ socket.io-1.3.5.js:1Manager @ socket.io-1.3.5.js:1lookup @ socket.io-1.3.5.js:1(anonymous function) @ chat:11

**Comment by caio-ribeiro-pereira** [comment]
@egamorim mais uma vez peço por favor, vc poderia postar no seu github o projeto inteiro pois assim ficará mais facil te ajudar....

**Comment by egamorim** [comment]
Segue: https://github.com/egamorim/NTalk

Obrigado

**Comment by caio-ribeiro-pereira** [comment]
Achei o bug @egamorim no seu app.js você ainda esta fazendo um listen do servidor através da função:

``` javascript
app.listen(3000);
```

Sendo que para o socket.io funcionar junto ao express, é necessário carregar o módulo `http` e fazer um listen através do http e não mais pelo app do express. Tanto é que no topo você carrega o servidor da seguinte maneira:

``` javascript
app = express(), 
server = require('http').Server(app), 
io = require('socket.io')(server);
```

E apartir desse trecho o servidor deve fazer um listen pela variável server e não mais pelo app. Então faça a seguinte alteração que vai funcionar:

``` javascript
server.listen(3000)
```

Obs.: O resto do código que chama a variável `app` deve continuar do jeito que esta.

**Comment by egamorim** [comment]
Mais uma vez muito obrigado.

**Comment by caio-ribeiro-pereira** [comment]
Show!

**Comment by egamorim** [comment]
E parabéns pelo livro, muito bom!!!!

**Comment by caio-ribeiro-pereira** [comment]
Obrigado!
