### ISSUE TITLE
Sessão única para cada usuário

### ISSUE THREAD

**Issue by andremw** [caio-ribeiro-pereira/livro-nodejs#17]
Eu constatei que a sessão não é única para cada novo usuário e por isso os exemplos não estão funcionando corretamente, pois o usuário da sessão é sempre sobrescrito com o último a logar no sistema, mesmo no projeto pronto do seu repositório. Tem algum passo pra que esse problema seja resolvido que talvez eu tenha pulado?

EDIT: Reparei que com uma janela normal e uma em modo privado funciona.. Mas duas iguais (normais ou privadas) não vai..

**Comment by caio-ribeiro-pereira** [comment]
Olá, a sessão em duas abas do browser é sobreescrita mesmo, isso é comportamento de alguns browsers e não tem nada relacionado com webapp. Antigamente duas abas eram consideradas duas sessões mas já faz um tempinho q esse comportamento mudou pelo menos no chrome e firefox. E isso é algo q nao tem como contornar, pq como disse antes é algo dos browsers. A solução mesmo é fazer o q vc fez: uma aba normal e uma aba privada.

**Comment by andremw** [comment]
Eu esqueci de falar isso, mas eu abri duas *janelas* e não abas.. Por isso achei estranho...

**Comment by caio-ribeiro-pereira** [comment]
Cara isso eh normal, pq a sessão mantem um cookie no browser. Que somente
em modo privado é reconhecido como novo usuário

Att,
Caio Ribeiro Pereira
Software Engineer
http://crpwebdev.com
