### ISSUE TITLE
session.io + clusters

### ISSUE THREAD

**Issue by andremw** [caio-ribeiro-pereira/livro-nodejs#18]
Fazendo alguns testes na aplicação após utilizar clusters e redis pra controlar as sessões, percebi que as mensagens do chat não estavam sendo enviadas de um usuário para outro. Verifiquei no dev tools as requisições e lá estavam sendo exibidas várias delas falhando, com status 400 (fora que o uso de websocket não estava mais funcionando), após clicar no botão enviar:

![400](https://cloud.githubusercontent.com/assets/878746/7551566/8f8bdcc2-f663-11e4-9c99-aade0ddb5a00.png)

Todas as requisições continham a mensagem: *Session ID unknown*.

Depois de tentar debugar o código, verificando se tinha algo errado ou diferente dos teus exemplos, fui procurar no Google e achei essa issue no github falando do mesmo problema:

https://github.com/Automattic/socket.io/issues/1503#issuecomment-58615215

Em um dos comentários um cara diz pra utilizar o módulo *sticky-session* e esse problema é resolvido.

Tentei fazer funcionar e consegui. As alterações que fiz foram poucas:

    //app.js....
    sticky(server).listen(3000, function () {
        console.log('NTalk no ar!');
    });

e removi a última linha que continha o module.exports = app;

Funcionou normalmente. Rodando esse arquivo o sticky-session já cria os clusters, não sendo mais necessário utilizar o clusters.js.

Você já tinha notado isso, Caio? Não achei nenhuma issue sobre isso, então resolvi comentar.
Se você não tiver nenhuma ressalva, acho que seria bom comentar sobre isso na próxima atualização do livro.

Abraço,

EDIT: Outro link interessante que fala sobre isso (e também menciona o sticky-session) é do próprio 
socket.io: [socket.io/sticky-load-balancing](http://socket.io/docs/using-multiple-nodes/#sticky-load-balancing)

**Comment by caio-ribeiro-pereira** [comment]
Olá @andremw enquanto estive desenvolvendo esse projeto piloto eu não tive esses problemas, porém não cheguei a fazer um teste desses em um ambiente de produção com múltiplos usuários acessando.
Realmente o uso do `sticky-session` é valido e vou adicionar ele na lista de updates do livro.
Obrigado!
