### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by bdadev** [caio-ribeiro-pereira/livro-nodejs#2]
Olá Caio, blz.
Refiz mais de 3x o capitulo 4 e só tenho retorno de um erro no navegador, abaixo o erro:

<pre>
  Error: No default engine was specified and no extension was provided. <br /> at new View (c:\wamp\www\ntalk\node_modules\express\lib\view.js:41:42) <br /> at Function.app.render (c:\wamp\www\ntalk\node_modules\express\lib\application.js:486:12) <br /> at ServerResponse.res.render (c:\wamp\www\ntalk\node_modules\express\lib\response.js:798:7) <br /> at HomeController.index (c:\wamp\www\ntalk\controllers\home.js:4:8) <br /> at callbacks (c:\wamp\www\ntalk\node_modules\express\lib\router\index.js:164:37) <br /> at param (c:\wamp\www\ntalk\node_modules\express\lib\router\index.js:138:11) <br /> at pass (c:\wamp\www\ntalk\node_modules\express\lib\router\index.js:145:5) <br /> at Router._dispatch (c:\wamp\www\ntalk\node_modules\express\lib\router\index.js:173:5) <br /> at Object.router (c:\wamp\www\ntalk\node_modules\express\lib\router\index.js:33:10) <br /> at next (c:\wamp\www\ntalk\node_modules\express\node_modules\connect\lib\proto.js:193:15)
</pre>

Não consigo fazer nossa aplicação de exemplo. Será que tem haver com a instalação global no express.

Meu sistema operacional é windows 8.1 64bits

**Comment by JonatanLima** [comment]
Olá Caio, sou novo em Node.js, dei uma olhada nos problemas anteriores, estou para entrar na sessão 5.3 Criando rotas no padrão REST, mesmo criando o arquivo "usuario.js" no diretório "models", recebo o erro :

 TypeError: Cannot read property 'usuario' of undefined at HomeController.login (/home/jonatan/ntalk/controllers/home.js:9:29) at callbacks (/home/jonatan/ntalk/node_modules/express/lib/router/index.js:164:37) at param (/home/jonatan/ntalk/node_modules/express/lib/router/index.js:138:11) at pass (/home/jonatan/ntalk/node_modules/express/lib/router/index.js:145:5) at Router._dispatch (/home/jonatan/ntalk/node_modules/express/lib/router/index.js:173:5) at Object.router (/home/jonatan/ntalk/node_modules/express/lib/router/index.js:33:10) at next (/home/jonatan/ntalk/node_modules/express/node_modules/connect/lib/proto.js:193:15) at Object.expressInit [as handle] (/home/jonatan/ntalk/node_modules/express/lib/middleware.js:30:5) at next (/home/jonatan/ntalk/node_modules/express/node_modules/connect/lib/proto.js:193:15) at Object.query [as handle] (/home/jonatan/ntalk/node_modules/express/node_modules/connect/lib/middleware/query.js:45:5)

executei todos os passos até chegar a 5.3, consigo acessar a página inicial, mas ao fazer o login recebo este erro, como se não tivesse criado models/usuario.js.

**Comment by JonatanLima** [comment]
É como se eu não conseguisse ler <input type="text" name="usuario[nome]" placeholder="Seu nome">.

**Comment by caio-ribeiro-pereira** [comment]
Cara, tem como vc commitar no github seu projeto e mandar o link para eu ver todo código?

**Comment by JonatanLima** [comment]
Opa, está aqui Caio: https://github.com/JonatanLima/EstudosNode.js.git

**Comment by caio-ribeiro-pereira** [comment]
Acabei de ver seu código, faça as seguintes modificações:
1) remove a pasta `bin` (ela não é usada e nem o arquivo www)
2) em `app.js` execute a função `load()` depois das declarações de middlewares `app.use()` e antes do carregamento do servidor `app.listen()`
3) em `controllers/home.js` remova o código `var Usuario = app.models.usuario;` afinal ele não esta sendo usado no momento (ele será usado no futuro) porém como não tem código do `models/usuario.js` ele ta carregando um módulo vazio e gerando esse erro.

**Comment by JonatanLima** [comment]
Muito obrigado pela atenção Caio!

**Comment by caio-ribeiro-pereira** [comment]
Denada! abs!

**Comment by gustavolivas** [comment]
Olá Caio,

Qual é a versão do express utilizada nos exemplos do livro?

**Comment by caio-ribeiro-pereira** [comment]
Na versao atual do livro utilizo express 4.x e socket.io 1.x

Att,
Caio Ribeiro Pereira
Founder & CTO at 99folks.com
http://crpwebdev.com

**Comment by ejhones** [comment]
Ola Caio, estava implementando o capitulo 7 porem quando fui rodar a aplicação apareceu o seguinte erro:

ntalk/controllers/contatos.js:6
      Usuario.findById(_id, function (erro, usuario) {
             ^

SyntaxError: Unexpected token .
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)

Poderia me ajudar.

**Comment by caio-ribeiro-pereira** [comment]
Tem algum erro de sintax nesse código, por favor, copie aqui o código:
controllers/contatos.js para que eu possa te ajudar :)

Regards,
Caio Ribeiro Pereira
About: http://crpwebdev.com

**Comment by ejhones** [comment]
module.exports = function(app){
  var Usuario = app.models.usuario;
  var ContatosController = {
    index: function (req, res) {
      var _id = req.session.usuario._id,
      Usuario.findById(_id, function (erro, usuario) {
        var contatos = usuario.contatos;
        var resultado = { contatos: contatos};
        res.render('contatos/index', resultado);
      });
    },
    create: function(req, res){
      var _id = req.session.usuario._id,
      Usuario.findById(_id, function (erro, usuario) {
        var contato = req.body.contato;
        var contatos = usuario.contatos;
        contatos.push(contato);
        usuario.save(function () {
          res.render('contatos/index', resultado);
        });
      });
    },
    show: function (req, res) {
      var _id = req.session.usuario._id,
      Usuario.findById(_id, function (erro, usuario) {
        var contatoID = req.params.id;
        var contato = usuario.contatos.id(contatoID);
        var resultado = {contato : contato}
        res.render('contatos/show', resultado);
      });
    },
    edit: function (req, res) {
      var _id = req.session.usuario._id,
      Usuario.findById(_id, function (erro, usuario) {
        var contatoID = req.params.id;
        var contato = usuario.contatos.id(contatoID);
        var resultado = {contato : contato}
        res.render('contatos/edit', resultado);
      });
    },
    update: function (req, res) {
      var _id = req.session.usuario._id,
      Usuario.findById(_id, function (erro, usuario) {
        var contatoID = req.params.id;
        var contato = usuario.contatos.id(contatoID);
        contato.nome = req.body.contato.nome;
        contato.email = req.body.contato.email;
        usuario.save(function () {
          res.redirect('/contatos');
        });
      });
    },
    destroy: function (req, res) {
      var _id = req.session.usuario._id,
      Usuario.findById(_id, function (erro, usuario) {
        var contatoID = req.params.id;
        usuario.contatos.id(contatoID).remove();
        usuario.save(function () {
          res.redirect('/contatos');
        });
      });
    }
  };
  return ContatosController;
};

**Comment by caio-ribeiro-pereira** [comment]
@ejhones teu código sem formatação fica dificil de entender onde há erro de síntaxe. Faz o seguinte, me mande o link github do seu projeto para eu analisar o código inteiro.

**Comment by ejhones** [comment]
link do projeto no git: https://github.com/ejhones/nodejs.git

**Comment by caio-ribeiro-pereira** [comment]
@ejhones ja entendi o problema, vc nao instalou as dependências necessárias.

Teu `package.json` só tem o `express`, `cookie-parser`, `body-parser` e `ejs`, mas cade o `mongoose`, `socket.io`, `express-load`, `express-session`, `method-override`?

roda esse comando: `npm install --save mongoose socket.io express-load express-session method-override`

que provavelmente vai resolver seu problema :)

**Comment by fernando-pascoal** [comment]
Caio, quando vou instalar as dependencias 'npm install' me retorna um erro. Vou postar o erro abaixo: 
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:116:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:71:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Fernando\Documents\WORKSPACES\nodejs\livro-nodejs\projeto\ntalk\node_modules\hiredis
gyp ERR! node -v v4.2.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"4.2.2","npm":"2.14.7"})

**Comment by caio-ribeiro-pereira** [comment]
Vc esta no windows, e tem certos modulos nodejs que precisam do python,
entao instale-o para resolver esse problema.

Regards,
Caio Ribeiro Pereira
About: http://crpwebdev.com
