### ISSUE TITLE
ERRO, iniciando com Express

### ISSUE THREAD

**Issue by egamorim** [caio-ribeiro-pereira/livro-nodejs#20]
Boa tarde.

Estou acompanhando o livro, mas na pagina 45 ao tentar executar o comando node app.js, retorna o seguinte erro:

Error: Cannot find module './routes/index'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (D:\pessoal\estudo\nodejs\book\ntalk\app.js:2:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)

Pode me ajudar por favor?

Valeu

**Comment by caio-ribeiro-pereira** [comment]
Ola, por favor envie o codigo do app.js para eu analisar o erro...

Att,
Caio Ribeiro Pereira
Software Engineer
http://crpwebdev.com

**Comment by egamorim** [comment]
Segue:

var express = require('express');
var load = require('express-load');
var app = express();

app.set('views', __dirname + '/views');
app.set('view engine','ejs');
app.use(express.static(__dirname + '/public'));

load('models')
	.then('controllers')
	.then('routes')
	.into(app);
	
app.listen(3000, function(){
	console.log("Ntalk in on.")
})

**Comment by caio-ribeiro-pereira** [comment]
Bom, seu app.js esta ok, entao faça o seguinte, se existir um arquivo
routes/index.js pode apagar ele, pois ele é codigo antigo que apartir do
momento que no livro se começa a criar um projeto, eu recomendo a exclusão
desse arquivo e talvez vc pulou essa etapa.

Por favor, exclua o arquivo routes/index.js rode o projeto e depois se o
problema continuar me avise.

Att,
Caio Ribeiro Pereira
Software Engineer
http://crpwebdev.com

**Comment by egamorim** [comment]
Eu apaguei, na pasta routes há apenas o arquivo home.js, conforme sua orientação.

**Comment by egamorim** [comment]
Não sei porque mas quando substituí o trecho:

load('models')
.then('controllers')
.then('routes')
.into(app);

por:
load('models').into(app);
load('controllers').into(app);
load('routes').into(app);

funcionou.

Valeu

**Comment by caio-ribeiro-pereira** [comment]
Nossa desse jeito nao eh recomendavel pois os models e controlers nao
estarao compartilhados atraves da variavel app, o certo eh rodar o load do
jeito anterior.

Att,
Caio Ribeiro Pereira
Software Engineer
http://crpwebdev.com

**Comment by egamorim** [comment]
Mas da outra maneira não funcionou, o que você acha que pode ser?

**Comment by caio-ribeiro-pereira** [comment]
Cara commita no seu github o projeto inteiro e me mande o link para eu
analisar

Att,
Caio Ribeiro Pereira
Software Engineer
http://crpwebdev.com

**Comment by egamorim** [comment]
Cara, não sei porque estava acontecendo isso, mas eu voltei do jeito anterior e funcionou.

De qualquer forma muito obrigado pela ajuda.

**Comment by egamorim** [comment]
Mais uma dúvida ... pelo menos eu não percebi se o livro esclarece:

eu defino um controller:
module.exports = function(app){
	var ContatoController = {
		index: function(req, res){
			var usuario = req.session.usuario;
			var contatos = usuario.contatos;
			var params = {usuario: usuario, contatos: contatos};
			res.render('contatos/index', params);
		}
          // ... continuação do controller

ai no arquivo de route, eu tenho o seguinte:

app.get('/contatos', contatos.index);

Onde está relacionado o controller com o contatos dentro do app.get ? 
Como ele sabe que é essa action e não a definida no arquivo home.js ?

**Comment by caio-ribeiro-pereira** [comment]
Cara acho q vc esta lendo uma versao antiga do livro, pois esses problemas
nao existem na versao atual.

Basicamente a funcao load()  injeta a variavel app para todos os modulos
que existirem nas pastas que vc citar nessa funcao utilizarem ela.

Esse modulo faz uma injeçao de dependencias.

Att,
Caio Ribeiro Pereira
Software Engineer
http://crpwebdev.com
