### ISSUE TITLE
Instalação módulo mongoose

### ISSUE THREAD

**Issue by ped-bernardo** [caio-ribeiro-pereira/livro-nodejs#21]
Caio,

Juro que tentei resolver os problemas pelas vias normais (google) antes de vir aqui abrir uma Issue, mas tô penando tem uns dias. Acontece que desde que cheguei no capítulo da integração com banco não consegui seguir adiante. Tentando tantas alternativas instalei o módulo node-gyp global, e agora sempre que tento instalar tanto o socket.io quanto mongoose é gerada essa saída de erro:

 > kerberos@0.0.12 install /home/pedro/projects/ntalk/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/home/pedro/projects/ntalk/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos/build'
  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
make: Leaving directory `/home/pedro/projects/ntalk/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos/build'
npm WARN installMany nopt was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
npm WARN installMany npmlog was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
npm WARN installMany request was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
npm WARN installMany semver was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
npm WARN installMany tar was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
npm WARN installMany tar-pack was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
npm WARN installMany mkdirp was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
npm WARN installMany rc was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
npm WARN installMany rimraf was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
|
> bson-ext@0.1.7 install /home/pedro/projects/ntalk/node_modules/mongoose/node_modules/bson/node_modules/bson-ext
> (node-pre-gyp install --fallback-to-build) || (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/home/pedro/projects/ntalk/node_modules/mongoose/node_modules/bson/node_modules/bson-ext/build'
  CXX(target) Release/obj.target/bson/ext/bson.o
  SOLINK_MODULE(target) Release/obj.target/bson.node
  SOLINK_MODULE(target) Release/obj.target/bson.node: Finished
  COPY Release/bson.node
make: Leaving directory `/home/pedro/projects/ntalk/node_modules/mongoose/node_modules/bson/node_modules/bson-ext/build'
ejs@2.3.1 node_modules/ejs

cookie-parser@1.3.5 node_modules/cookie-parser
├── cookie@0.1.3
└── cookie-signature@1.0.6

express-load@1.1.14 node_modules/express-load
└── async@0.2.9

method-override@2.3.3 node_modules/method-override
├── methods@1.1.1
├── vary@1.0.0
├── parseurl@1.3.0
└── debug@2.2.0 (ms@0.7.1)

express-session@1.11.2 node_modules/express-session
├── utils-merge@1.0.0
├── cookie-signature@1.0.6
├── cookie@0.1.2
├── on-headers@1.0.0
├── parseurl@1.3.0
├── depd@1.0.1
├── crc@3.2.1
├── uid-safe@2.0.0 (base64-url@1.2.1)
└── debug@2.2.0 (ms@0.7.1)

express@4.12.4 node_modules/express
├── merge-descriptors@1.0.0
├── utils-merge@1.0.0
├── cookie-signature@1.0.6
├── methods@1.1.1
├── fresh@0.2.4
├── cookie@0.1.2
├── escape-html@1.0.1
├── range-parser@1.0.2
├── content-type@1.0.1
├── finalhandler@0.3.6
├── vary@1.0.0
├── parseurl@1.3.0
├── serve-static@1.9.3
├── content-disposition@0.5.0
├── path-to-regexp@0.1.3
├── depd@1.0.1
├── qs@2.4.2
├── on-finished@2.2.1 (ee-first@1.1.0)
├── etag@1.6.0 (crc@3.2.1)
├── debug@2.2.0 (ms@0.7.1)
├── proxy-addr@1.0.8 (forwarded@0.1.0, ipaddr.js@1.0.1)
├── send@0.12.3 (destroy@1.0.3, ms@0.7.1, mime@1.3.4)
├── type-is@1.6.2 (media-typer@0.3.0, mime-types@2.0.13)
└── accepts@1.2.7 (negotiator@0.5.3, mime-types@2.0.13)

body-parser@1.12.4 node_modules/body-parser
├── content-type@1.0.1
├── bytes@1.0.0
├── depd@1.0.1
├── raw-body@2.0.2 (bytes@2.1.0)
├── qs@2.4.2
├── on-finished@2.2.1 (ee-first@1.1.0)
├── debug@2.2.0 (ms@0.7.1)
├── iconv-lite@0.4.8
└── type-is@1.6.2 (media-typer@0.3.0, mime-types@2.0.13)

mongoose@4.0.4 node_modules/mongoose
├── regexp-clone@0.0.1
├── sliced@0.0.5
├── muri@1.0.0
├── hooks-fixed@1.0.1
├── mpromise@0.5.4
├── kareem@1.0.1
├── mpath@0.1.1
├── async@0.9.0
├── ms@0.1.0
├── mquery@1.5.1 (debug@0.7.4, bluebird@2.9.9)
├── mongodb@2.0.33 (readable-stream@1.0.31, mongodb-core@1.1.32)
└── bson@0.3.2 (bson-ext@0.1.7)

**Comment by caio-ribeiro-pereira** [comment]
Olá @ped-bernardo a aplicação não funciona depois dessa instalação? Pois essas mensagens de warning não me parece que tem problema na instalação. De qualquer forma um detalhe que pode gerar problemas é que você esta instalando o `mongoose@4.0.4` e no livro estou explicando como trabalhar com a versão `mongoose@3.8.0`, recomendo que você utilize essa versão antiga citada no livro, ou então procure nos changelogs do mongoose o que há de diferente nessas versões para vc implementar usando a nova versão.

**Comment by ped-bernardo** [comment]
@caio-ribeiro-pereira,

Obrigado pelo retorno! A aplicação não estava funcionando, mas nessa coisa de tentar solucionar passei a aplicação para o Ubuntu e larguei o Windows. Fixei a versão do mongoose em ~3.8.x, e fora esses warnings está tudo funcionando e salvando no mongo! \o/

Devo me preocupar com esses warnings? Não faço a menor idéia do que se trata.

Abraço.

**Comment by caio-ribeiro-pereira** [comment]
Que bom que rodou e que bom que vc migrou para linux, pois o node roda completo em ambiente Unix/Linux. 

Os warnings de npm install, estão relacionados a algumas configs do seu sistema operacional com linguagem C e node-gyp, até hj recebo alguns warnings mas nunca me deram dores de cabeça.
