### ISSUE TITLE
Express 4

### ISSUE THREAD

**Issue by ped-bernardo** [caio-ribeiro-pereira/livro-nodejs#22]
@caio-ribeiro-pereira 
Existe a possibilidade de rolar uma atualização do código para o express v4? Andei estudando e houveram algumas alterações, principalmente com o uso do express.Router() para definição de rotas.

E outra questão, pelo que andei olhando nos tutoriais, não achei nenhum que usasse a abordagem de controllers, normalmente o pessoal deixa toda a lógica dentro do próprio arquivo de rotas. Existe uma melhor prática? Vi um pessoal defendendo a prática citada pelo fato de centralizar a lógica em um único lugar, mas achei interessante a tua abordagem, parece mais organizado.

Abraço.

**Comment by caio-ribeiro-pereira** [comment]
Olá @ped-bernardo o meu livro atual esta usando Express 4 sim, você pode manter a organização de routes dentro da variável `var app = express()` ou `var router = express.Router()` que em ambos tudo vai funcionar sim.

Outra coisa, como no node.js muita organização de código é aceita e flexível para o desenvolvedor organizar do jeito que ele quiser, no meu livro eu fiz questão de manter lógicas no `controllers` ao invés de fazer tudo diretamente no routes, pois foi opção minha e cada um pode escolher manter as lógicas no controllers ou routes que o app vai funcionar, o motivo pelo qual escolhi controllers foi para deixar mais separado as lógicas e também pra deixar num padrão mais próximo do Ruby On Rails e também de frameworks como Sails.js e Geddy do Node.js.

De qualquer forma fique tranquilo que os códigos desse repositório e do livro ainda funcionam nos frameworks atuais.

**Comment by ped-bernardo** [comment]
@caio-ribeiro-pereira 
Valeu pelo retorno.

Sim, entendo que funcione sem o uso do express.Router, se não for muito - hehe -, sabe dizer se há uma vantagem sobre uma das utilizações ou é só uma variação? Imaginei que com a criação desse novo recurso no express4, e como grande parte dos tutorais utilizam, fosse de boa prática o uso sobre a antiga forma com app = express().

Estive tentando utilizar essa abordagem de rotas e controllers com o uso do Router mas ainda tô pegando o jeito com node, entendendo a questão de escopo e funcionamento do exports e require, mas não vem ao caso...

**Comment by caio-ribeiro-pereira** [comment]
A vantagem de usar `express.Router` é que ele permite você criar várias routes de forma encadeada e também é possível criar middlewares específicos para um determinado grupo de routes.
