### ISSUE TITLE
Sessão 6.3 do livro (Mensagens não aparecem na tela)

### ISSUE THREAD

**Issue by valeriasilva** [caio-ribeiro-pereira/livro-nodejs#23]
Prezado Caio, não sei se este é o melhor lugar para reportar dúvidas. De todo modo, peço desculpas caso não seja.
Estou acompanhando o livro de Node.JS (versão mais atual). Ao executar o código do chat referente à sessão 6.3 a mensagem enviada não é mostrada na tela. Talvez eu esteja esquecendo de algo no código, mas revisei esta sessão várias vezes. Alguma ideia do que pode ser?

**Comment by caio-ribeiro-pereira** [comment]
Olá @valeriasilva continue lendo o livro até chegar na sessão 7 ou 8 (não lembro bem a sessão), pois nelas você aprenderá como persistir histórico do chat usando banco de dados redis :)

**Comment by valeriasilva** [comment]
Caio, dando continuidade no livro o chat começou a dar certo. Provavelmente foi algo que eu digitei errado no código. Bom, agradeço pelo seu feedback. Não quero te incomodar, mas, gostaria de saber se posso continuar reportando dúvidas por aqui.. Grata!!

**Comment by caio-ribeiro-pereira** [comment]
@valeriasilva nao se preocupe em incomodar, o importante eh vc aprender! Fique a vontade pra reportar issues aqui ou postar no grupo deste livro https://groups.google.com/forum/#!forum/livro-nodejs

Bons estudos!
