### ISSUE TITLE
Bugs Capitulo 5

### ISSUE THREAD

**Issue by romagnolocesar** [caio-ribeiro-pereira/livro-nodejs#27]
Boa noite, encontrei 2 Bugs ao finalizar o capitulo 5, mas felizmente também achei a solução:

=====ERRO=====
index.ejs:20 18| 19| >> 20| <% contatos.forEach(function(contato, index) { %> 21| 22| <%- contato.nome %> 23| <%- contato.email %> contatos is not defined
--------------------------------------------------------------------------------------------------------------

arquivo: controllers/contatos.js

=====ORIGINAL=====
index: function(req, res) {
   var usuario = req.session.usuario
   ,contatos = [usuario.contatos] <-- quando criado a variavel contatos e params assim a view não estava reconhecendo, e como usuario.contatos já era um objeto criado no home.js, acabava ficando [[objeto]];
  ,params = {usuario: usuario};
   res.render('contatos/index', params);
 },

=====EDITADO=====
index: function(req, res) {
   var usuario = req.session.usuario;
   contatos = usuario.contatos; <-- desse jeito funcionou
   params = {usuario: usuario};
   res.render('contatos/index', params);
 },

**Comment by caio-ribeiro-pereira** [comment]
Esse bug ja foi corrigido, provavelmente vc deve ter uma versão antiga do
livro.

Att,
Caio Ribeiro Pereira
Founder & CTO at 99folks.com
http://crpwebdev.com

**Comment by romagnolocesar** [comment]
Obrigado Caio!! Provavelmente estou, teria como você me passar uma versão atualizada? comprei faz um tempo e deve ter vindo desatualizado mesmo.

**Comment by caio-ribeiro-pereira** [comment]
É só vc acessar http://livros.casadocodigo.com.br/ com sua conta e baixar gratuitamente o ebook atualizado.
