### ISSUE TITLE
Pagina 44

### ISSUE THREAD

**Issue by ricardocarrer** [caio-ribeiro-pereira/livro-nodejs#28]
Caio, 

Na pagina 44 tem um trecho que pede para criar o arquivo routes/home.js, porém não informa para criar o arquivo controllers/home.js com o trecho abaixo:

module.exports = function(app) {
  var HomeController = {
    index: function(req, res) {
      res.render('home/index');
} };
  return HomeController;
};

Trecho do Livro:
Repare que por causa do express-load, a variável app já possui um su- bobjeto chamado controllers. Neste caso, o app.controllers.home está se referenciando ao arquivo
module.exports = function(app) {
  var HomeController = {
    index: function(req, res) {
      res.render('home/index');
} };
  return HomeController;
};

**Comment by caio-ribeiro-pereira** [comment]
Olá @ricardocarrer esse bug já foi resolvido, provavelmente vc deve ter uma versão antiga do livro, outra coisa que recomendo é que continue lendo o livro, pois alguns trechos faltantes, pode aparecer em páginas futuras.
Obrigado pelo feedback!

**Comment by ricardocarrer** [comment]
Estou lendo sim. Talvez a casa do código ainda não tenho atualizado, baixei segunda o ebook.

Abraços

**Comment by rjekstein** [comment]
Caio, comprei o livro a 3 semanas e este bug ainda permanece na versão online ebook.
