### ISSUE TITLE
Problema com Comunicação one-to-one Cap 6.8

### ISSUE THREAD

**Issue by pedro-hos** [caio-ribeiro-pereira/livro-nodejs#29]
@caio-ribeiro-pereira tudo bem? Estou seguindo meus estudos com o seu livro (parabéns, sou programador Java e estou conseguindo aprender bastante sobre node com ele etc.)

Porém, estou com um problema no Cap. 6.8, onde temos que fazer com que cada sala mantenha uma conversa com apenas 2 contatos, que ele crie uma sala. O problema acontece na hora de enviar a mensagem, porém não aparece nenhum erro nem no console do mac, nem no do browser. 

Se quiser, da uma olhada no meu código: https://github.com/pedro-hos/courses/tree/master/node/ntalk

Agradeço desde já.

**Comment by caio-ribeiro-pereira** [comment]
@pedro-hos não entendi qual é o problema, o que acontece na hora de enviar a mensagem? Lembrando que vc esta no cap 6, e é normal o chat não manter histórico ou perder mensagens, afinal você não implementou ainda o Redis como banco para manter histórico de mensagens, isso você verá no próximo capítulo.
Se for esse o problema, por favor, continue lendo o livro até o final e feche essa issue.
Obrigado!

**Comment by pedro-hos** [comment]
Para mim não aparece nenhum erro. Mas quando dou um send na mensagem ele não esta enviando. Não esta "mostrando na tela"

**Comment by caio-ribeiro-pereira** [comment]
@pedro-hos seu código esta aparentemente ok, só recomendo que continue lendo e seguindo o livro, pois nem todo código de uma certa página vai funcionar, tem certos trechos que só irão funcionar em páginas futuras.
Outra coisa que recomendo é que você limpe o cookie do projeto, pois entre cap5 e cap6, é explicado como mudar os dados de cookie/session, e isso impacta no handshake do socket.io, pelo qual pode acabar impedindo o funcionamento da aplicação também.

**Comment by pedro-hos** [comment]
Beleza então vou seguir com o estudo. Obrigado
