### ISSUE TITLE
Cap. 6 client.on('join')

### ISSUE THREAD

**Issue by jjduarte** [caio-ribeiro-pereira/livro-nodejs#30]
Ao finalizar o cap 6 os usuários não conseguem entrar na mesma "sala" criada através do hash. 
A função client.on('join') não recebe uma sala pelo parâmetro e sempre cria uma nova. Isso deve acontecer pq quando a sala é criada pelo primeiro que entra não é atualizado a sala para o outro usuário para que este então possa entrar dentro da mesma sala. 

Alguma idéia de onde isto pode estar falhando? Obrigado.

**Comment by caio-ribeiro-pereira** [comment]
Ola joao o fluxo do chat funciona somente da seguinte maneira: o usuario 1
entra no chat, e somente o usuario 2 podera entra na sala, se o usuario 1
mandar uma mensagem (pelo qual envia o hash da sala e atualiza o status da
lista de contatos do usuario 2 para entra na sala) fiz isso pois o usuario
1 poderia entra e sair da sala sem mandar msg e nisso iria gerar o hash
desnecessariamente.

Se vc seguiu esse fluxo e msmo assim deu erro, volte aqui com github do seu
projeto para eu avaliar, caso contrario, se esse fluxo estiver ok, por
favor feche essa issue.

Abs!

Att,
Caio Ribeiro Pereira
Founder & CTO at 99folks.com
http://crpwebdev.com

**Comment by jjduarte** [comment]
A primeira mensagem acaba se "perdendo" no fluxo certo? 
Mas o resto funcionou perfeitamente.

**Comment by caio-ribeiro-pereira** [comment]
Isso, esta correto, pois vc esta ainda no cap6, somente no cap7 vc tera
banco de dados para persistir as msgs num historico de chat :)

Att,
Caio Ribeiro Pereira
Founder & CTO at 99folks.com
http://crpwebdev.com

**Comment by jjduarte** [comment]
Obrigado Caio!

**Comment by DaniloPaixaoJesus** [comment]
Segui exatamente o que está no livro, mas a função client.on('join') não é chamada de forma alguma. Vi que o repositório do git do livro possui o app com a versão mais nova do express e do socket.io.

**Comment by caio-ribeiro-pereira** [comment]
Provavelmente vc esta usando uma versão antiga do meu livro, pois o
repositorio esta atualizado com o livro.

Regards,
Caio Ribeiro Pereira
About: http://crpwebdev.com
