### ISSUE TITLE
Dúvida sobre socketIO 

### ISSUE THREAD

**Issue by geanfelipe** [caio-ribeiro-pereira/livro-nodejs#31]
Não entendi a diferença entre o socket.emit() e o socket.broadcast.emit().

**Comment by caio-ribeiro-pereira** [comment]
Ola Gean,

Essa diferença é bem explicada no livro, mas vou reforçar aqui:

socket.emit() quando é chamado no client-side ele apenas envia dados para o
servidor, e quando ele é chamado no server-side ele envia dados para o
cliente que executou socket.emit().

socket.broadcast.emit() é chamado apenas no server-side e ele basicamente
envia dados para todos os clientes conectados menos para o cliente que
chamou um socket.emit()

Regards,
Caio Ribeiro Pereira
About: http://crpwebdev.com

**Comment by geanfelipe** [comment]
Entendi!! Obrigado!

**Comment by geanfelipe** [comment]
Como poderia enviar uma msg a todos de uma sala menos para o que envia?
Tipo o cara tá digitando no chat daí eu enviar a A que B está digitando.

**Comment by caio-ribeiro-pereira** [comment]
A funçao socket.boradcast.emit() no server manda pra todos menos para o
usuario que mandou a msg

Regards,
Caio Ribeiro Pereira
About: http://crpwebdev.com
