### ISSUE TITLE
Capítulo 6 - Require- socket 

### ISSUE THREAD

**Issue by geanfelipe** [caio-ribeiro-pereira/livro-nodejs#32]
[dúvida de iniciante]
Olá caio,
acabei de terminar a sessão 6.7 do livro e tenho dúvida em relação a como chamar o script sockets/chat.js no app.js. No caso, o load('sockets').into(io) só torna o escopo global do app.js também escopo global dos scripts da pasta sockets. 
É isso? só fazendo o require(sockets/chat.js) faria necessário esse código ser executado?
projeto--> https://github.com/geanfelipe/livro-nodejs
agradeço

**Comment by geanfelipe** [comment]
Ah, aproveitei e coloquei tudo no app.js daí percebi que ele não mais enviando a mensagem pro outro usuário da mesma sala. 
Vou tentar descobrir o que é,,

**Comment by caio-ribeiro-pereira** [comment]
Olá @geanfelipe como vc ainda esta no capítulo 6, recomendo que você siga exatamente o que o livro pede, pq por mais que pareça meio estranho alguns código, eles serão explicados e refactorados nos capítulos seguintes.
O que você fez em chamar o sockets/chat.js e ao msmo tempo replicar a lógica desse script dentro de app.js não faz sentido, e não se preocupe com escopos globais no nodejs, que como disse, eles serão refactorados nos capítulos mais para frente.

**Comment by geanfelipe** [comment]
Beleza, obrigado!
