### ISSUE TITLE
Olá

### ISSUE THREAD

**Issue by carolgit** [caio-ribeiro-pereira/livro-nodejs#33]
estou usando o express 2.5.8

quando uso o comando o comando express ntalk --ejs , é criado um projeto de nome --ejs com dependecia jade

**Comment by caio-ribeiro-pereira** [comment]
Ola ana, vc deveria usar a versão 4.x do express, pois essa versão é muito
antiga e meu livro não da suporte a esta versão

Regards,
Caio Ribeiro Pereira
About: http://crpwebdev.com
