### ISSUE TITLE
Alternativas para o módulo Hi-Redis

### ISSUE THREAD

**Issue by ClausRT** [caio-ribeiro-pereira/livro-nodejs#35]
Olá. Como estou desenvolvendo o Ntalk em um computador windows, encontrei certos problemas ao chegar no capitulo 7. O Redis, que não é suportado oficialmente no windows, foi instalado de boa graças a isso: https://github.com/MSOpenTech/redis

Porém não consigo instalar o Hi-Redis, dando o famoso problema do "node-gyp rebuild". Apesar de ter visto várias soluções para o problema, nenhuma funcionou e depois de um dia e meio travado por causa disso eu decidi desistir do Hi-Redis.

Não existe nenhuma alternativa para esse modulo? Ou a possibilidade de não utiliza-lo no projeto do Ntalk?

Caso o problema com a instalação do Hi-Redis não tenha sido clara, deixo em anexo o relatório do erro.

[npm-debug.txt](https://github.com/caio-ribeiro-pereira/livro-nodejs/files/83327/npm-debug.txt)

**Comment by caio-ribeiro-pereira** [comment]
O hiredis eh opcional, infelizmente nao tem versao dele para windows, mas
vc pode prosseguir o projeto sem ele. Ele só é vantajoso em ambiente
unix/linux

Regards,
Caio Ribeiro Pereira
About: http://crpwebdev.com

**Comment by ClausRT** [comment]
Muito obrigado.
