### ISSUE TITLE
Erro na ligação home router x home controller

### ISSUE THREAD

**Issue by lucianoslimarj** [caio-ribeiro-pereira/livro-nodejs#36]
Ao instanciar a aplicação, estou tendo o seguinte erro:
c:\Cursos\nodejs\ntalk\node_modules\express\lib\router\index.js:140
  var search = 1 + req.url.indexOf('?');
                       ^
TypeError: Cannot read property 'indexOf' of undefined
    at Function.handle (c:\Cursos\nodejs\ntalk\node_modules\express\lib\router\index.js:140:27)
    at Object.router (c:\Cursos\nodejs\ntalk\node_modules\express\lib\router\index.js:46:12)
    at c:\Cursos\nodejs\ntalk\node_modules\express-load\lib\express-load.js:242:19

segue o home router:

**module.exports = function(app){
  var homeCtrl = app.controllers.home;
  console.log(">>>No router home<<<");
  app.get('/', homeCtrl.index);
};**

segue o home controller:

**module.exports = function(app){
  var homeController = {
    index : function(req, res ){
	  console.log(">>>No controller home<<<");
	  res.render('home/index');
	} 
  };
  return homeController;
}**

segue o app.js:

**var express = require('express')
     , load = require('express-load');
var app = express();
app.set('views', __dirname + '/views');
app.set('view engine', 'ejs');
app.use(express.static(__dirname + '/public'));
load('models').then('controllers').then('routes').into(app);
app.listen(3000, function(){
	console.log("Ntalk no ar!");
});
module.exports = app;**

É como se no start da aplicação, o "app.get('/', homeCtrl.index);" estive fazendo uma chamada ao index do controller e não passando o request.

Caio, pode me ajudar ?

**Comment by lucianoslimarj** [comment]
Caio, encontrei o problema: haviam alguns .js no diretorio routes. Esses .js seguiam uma codificação diferente, diferente da que o express-load espera.

**Comment by felipeaffonso** [comment]
Muito obrigado @lucianoslimarj, me ajudou demais!
Um outro projeto, mas enfim. Estava usando o consign para ler as minhas rotas (consign é o novo nome do express-load).
