### ISSUE TITLE
Dúvida sobre o chat

### ISSUE THREAD

**Issue by rodrigoaustincascao** [caio-ribeiro-pereira/livro-nodejs#37]
Boa noite!
Estou lendo seu livro e ele é muito bom.
Estou seguindo os exemplos e estou implementando o ntalk, estou no capítulo 6.6.
Fiz um teste com o chat abrindo dois navegadores e logando no ntalk, cada navegador com um usuário diferente e em  cada navegador criando e escolhendo contatos diferentes para conversar, só que no chat o usuário que realiza a conversa não é o usuário logado no sistema, mas sim o contato. É assim mesmo?
E a conversa vai para todos os navegadores e não privada para o contato, é isso mesmo?

Desde já grato pela atenção.

**Comment by caio-ribeiro-pereira** [comment]
Ola!

O chat esta bem simplificado, para vc simular corretamente um chat privado
1-1, eh necessário criar 2 contas, e cada conta adiciona o email da outra
conta, ambos precisam estar logado para que em seguida os contatos consigam
visualizar se ambos estao online, para depois um dos contatos iniciar uma
conversa com o outro.

Se um dos usuarios nao estiver logados, o chat nao vai funcionar direito. O
chat esta bem simplificado para uso didático, mas fique a vontade para
melhorá-lo em seus projetos.

Abs!

Regards,
Caio Ribeiro Pereira
About: http://crpwebdev.com

**Comment by rodrigoaustincascao** [comment]
Grato pela atenção!
