### ISSUE TITLE
Capitulo 4 - Configuração de Rotas

### ISSUE THREAD

**Issue by rjekstein** [caio-ribeiro-pereira/livro-nodejs#40]
Ola Caio, bom dia !

Durante o passo a passo em que voce ensina a realizar a primeira configuração de Rota, após segui os passos e rodo o comando node app.js, é exibida a mensagem "Ntalk no ar", no entanto ao acessar Localhost:3000 é exibido a mensagem "Cannot GET"

Consegue me ajudar ?

**Comment by caio-ribeiro-pereira** [comment]
Me mande o github do seu projeto que te ajudo sim

**Comment by rjekstein** [comment]
Caio, bom dia !

Achei o erro, o mesmo se encontra no livro, exatamente nesta parte : 

Repare que por causa do express-load, a variável app já possuiumsubobjeto
chamado controllers. Neste caso, o app.controllers.home
está se referenciando ao arquivo

module.exports = function(app) {
var HomeController = {
index: function(req, res) {
res.render('home/index');
}
};
return HomeController;
};

apenas criei o arquivo home.js no diretorio controller, porém no livro não tem essa orientação, fiz a aquisição a 4 semanas atras e com a ultima versão que esta no site porém este bug ainda persiste.

**Comment by caio-ribeiro-pereira** [comment]
Entendi, obrigado pelo bug report!   

Por favor, se o problema foi resolvido, feche essa issue, obrigado!  

Regards,
Caio Ribeiro Pereira
Developer, blogger and writter
About: http://crpwebdev.com
Blog: http://udgwebdev.com
