### ISSUE TITLE
Dois erros de execução no Windows 10

### ISSUE THREAD

**Issue by victorhit** [caio-ribeiro-pereira/livro-nodejs#41]
Olá Caio baixei o projeto NTALK para minha pasta do Git,** mas quando ao executar o comando "npm start" o Win 10 apresenta o seguinte erro:**

> node server

events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Program ENOENT
    at exports._errnoException (util.js:890:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Function.Module.runMain (module.js:449:11)
    at startup (node.js:146:18)
    at node.js:404:3

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE
npm ERR! ntalk@1.0.0 start: `node server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ntalk@1.0.0 start script 'node server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ntalk package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ntalk
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ntalk
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Victorugo\Documents\GitHub\naulas\ntalk\npm-debug.log

C:\Users\Victorugo\Documents\GitHub\naulas\ntalk>

**Quando ao executar o comando "node app.js" o Win 10 apresenta o seguinte erro:**

C:\Users\Victorugo\Documents\GitHub\naulas\ntalk>node app.js
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
Ntalk no ar.
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
    at RedisClient.on_error (C:\Users\Victorugo\Documents\GitHub\naulas\ntalk\node_modules\socket.io-redis\node_modules\redis\index.js:185:24)
    at Socket.<anonymous> (C:\Users\Victorugo\Documents\GitHub\naulas\ntalk\node_modules\socket.io-redis\node_modules\redis\index.js:95:14)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at emitErrorNT (net.js:1249:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

O caminho do projeto é seguinte: C:\Users\Victorugo\Documents\GitHub\naulas\ntalk>

Agradeço sua atenção e aguardo help...

**Comment by caio-ribeiro-pereira** [comment]
@victorhit cara....vc tem q instalar o MongoDB e tbm o Redis antes de rodar o projeto.

Outro detalhe, você tera q remover o módulo hiredis que esta nesse package.json, pois ele é um módulo para melhorar performance do Redis apenas no Unix/Linux incompatível com Windows, sem ele no Windows você não terá problemas e o projeto vai rodar, então faça a seguintes tarefas:

1) Instale o MongoDB (https://www.mongodb.org/downloads)
2) Instale o Redis (http://redis.io/download)
3) Rode: `rm -rf node_modules && npm remove hiredis --save && npm install && npm start`

Me avise se depois desse procedimento tudo deu certo eae feche essa issue, abs!

**Comment by romuloricoy** [comment]
Deu tudo certo, obrigado!

**Comment by caio-ribeiro-pereira** [comment]
Boaaa! Vou dar close nessa issue, abs!

**Comment by victorhit** [comment]
Caio instalei o mongoDB e o Redis instalei na minha pasta roaming onde ficam guardados os módulos gerais npm do computador. Instalei redis de forma local no projeto.
No projeto está da seguinte versão:
C:\Users\Victorugo\Documents\GitHub\naulas\ntalk> npm redis -v
3.8.3

Removi o hredis:
C:\Users\Victorugo\Documents\GitHub\naulas\ntalk> npm remove hiredis --save
C:\Users\Victorugo\Documents\GitHub\naulas\ntalk> npm install
C:\Users\Victorugo\Documents\GitHub\naulas\ntalk> npm start

O erro persiste.
 

De ultima tentativa instalei um executável desse endereço https://github.com/rgl/redis/downloads

Agradeço sua atenção e aguardo help...

**Comment by caio-ribeiro-pereira** [comment]
Mas o mongodb e redis sao servidores a parte, eles nao devem ficar na pasta
roaming do nodejs....e acredito que sera melhor instalar eles atraves de
seus respectivos instaladores que sao disponibilizados em seus sites, feito
isso vc tera q iniciar o servico do mongo e redis para depois rodar seu
servidor que vai se conectar com esses dbs.

Regards,
Caio Ribeiro Pereira
About: http://crpwebdev.com

**Comment by amandaclarck** [comment]
Você deu start nos dois bancos? Você tem que dar start no mongo e no redis. Abre o cmd como admin e dá start nele e em outro cmd você dá redis-server dentro da pasta de instalação do redis que ele starta também. Aí o redis vai aparecer um consolezinho falando que você não tá conectado, aí você digita qualquer besteira nele e dá enter e ele fala que você tá conectado.

Outra coisa, instala o Mongo no C: e o Redis eu instalei nos Arquivos de Programas.

**Comment by victorhit** [comment]
Caio no caso do Redis não é fornecido um arquivo .exe ou .msi no site, é apenas disponibilizada uma pasta com o para descompactar com o redis na versão 3.0.7.

Onde devo descompactar essa pasta?
Desinstalo a versão do redis 2.4.6 que instalei via .exe do site externo?
Desinstalo da pasta roaming para não haver conflitos?

Agradeço sua atenção...
________________________________
De: Caio Ribeiro Pereira <notifications@github.com>
Enviado: quinta-feira, 28 de abril de 2016 14:54:53
Para: caio-ribeiro-pereira/livro-nodejs
Cc: victorhit; Mention
Assunto: Re: [caio-ribeiro-pereira/livro-nodejs] Dois erros de execução no Windows 10 (#41)

Mas o mongodb e redis sao servidores a parte, eles nao devem ficar na pasta
roaming do nodejs....e acredito que sera melhor instalar eles atraves de
seus respectivos instaladores que sao disponibilizados em seus sites, feito
isso vc tera q iniciar o servico do mongo e redis para depois rodar seu
servidor que vai se conectar com esses dbs.

Regards,
Caio Ribeiro Pereira
About: http://crpwebdev.com
On Apr 28, 2016 13:51, "victorhit" <notifications@github.com> wrote:

> Caio instalei o mongoDB e o Redis instalei na minha pasta roaming onde
> ficam guardados os módulos gerais npm do computador. Instalei redis de
> forma local no projeto.
> No projeto está da seguinte versão:
> C:\Users\Victorugo\Documents\GitHub\naulas\ntalk> npm redis -v
> 3.8.3
>
> Removi o hredis:
> C:\Users\Victorugo\Documents\GitHub\naulas\ntalk> npm remove hiredis --save
> C:\Users\Victorugo\Documents\GitHub\naulas\ntalk> npm install
> C:\Users\Victorugo\Documents\GitHub\naulas\ntalk> npm start
>
> O erro persiste.
>
> De ultima tentativa instalei um executável desse endereço
> https://github.com/rgl/redis/downloads
>
> Agradeço sua atenção e aguardo help...
>
> -
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/caio-ribeiro-pereira/livro-nodejs/issues/41#issuecomment-215492182>
>

-

**Comment by caio-ribeiro-pereira** [comment]
O redis vem apenas com binarios de execucao via terminal. Pode colocar ele
em qualquer pasta, e para rodar vc tera que abrir o terminal, acessar a
pasta fo redis e rodar o coma do redis-server para ele iniciar o serviço.

Regards,
Caio Ribeiro Pereira
About: http://crpwebdev.com

**Comment by victorhit** [comment]
Caio fiz o seguinte comando que você falou :


C:\Users\Victorugo\Documents\GitHub\naulas\ntalk\node_modules\redis> redis-server

redis-server : O termo 'redis-server' não é reconhecido como nome de cmdlet, função, arquivo de script ou programa
operável. Verifique a grafia do nome ou, se um caminho tiver sido incluído, veja se o caminho está correto e tente
novamente.
No linha:1 caractere:1
+ redis-server
+ ~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (redis-server:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException


Será que não foi instalado?

Agradeço sua atenção...



________________________________
De: Caio Ribeiro Pereira <notifications@github.com>
Enviado: quinta-feira, 28 de abril de 2016 15:07:13
Para: caio-ribeiro-pereira/livro-nodejs
Cc: victorhit; Mention
Assunto: Re: [caio-ribeiro-pereira/livro-nodejs] Dois erros de execução no Windows 10 (#41)

O redis vem apenas com binarios de execucao via terminal. Pode colocar ele
em qualquer pasta, e para rodar vc tera que abrir o terminal, acessar a
pasta fo redis e rodar o coma do redis-server para ele iniciar o serviço.

Regards,
Caio Ribeiro Pereira
About: http://crpwebdev.com
On Apr 28, 2016 14:01, "victorhit" <notifications@github.com> wrote:

> Caio no caso do Redis não é fornecido um arquivo .exe ou .msi no site, é
> apenas disponibilizada uma pasta com o para descompactar com o redis na
> versão 3.0.7.
>
> Onde devo descompactar essa pasta?
> Desinstalo a versão do redis 2.4.6 que instalei via .exe do site externo?
> Desinstalo da pasta roaming para não haver conflitos?
>
> Agradeço sua atenção...
> ________________________________
> De: Caio Ribeiro Pereira <notifications@github.com>
> Enviado: quinta-feira, 28 de abril de 2016 14:54:53
> Para: caio-ribeiro-pereira/livro-nodejs
> Cc: victorhit; Mention
> Assunto: Re: [caio-ribeiro-pereira/livro-nodejs] Dois erros de execução no
> Windows 10 (#41)
>
> Mas o mongodb e redis sao servidores a parte, eles nao devem ficar na pasta
> roaming do nodejs....e acredito que sera melhor instalar eles atraves de
> seus respectivos instaladores que sao disponibilizados em seus sites, feito
> isso vc tera q iniciar o servico do mongo e redis para depois rodar seu
> servidor que vai se conectar com esses dbs.
>
> Regards,
> Caio Ribeiro Pereira
> About: http://crpwebdev.com
> On Apr 28, 2016 13:51, "victorhit" <notifications@github.com> wrote:
>
> > Caio instalei o mongoDB e o Redis instalei na minha pasta roaming onde
> > ficam guardados os módulos gerais npm do computador. Instalei redis de
> > forma local no projeto.
> > No projeto está da seguinte versão:
> > C:\Users\Victorugo\Documents\GitHub\naulas\ntalk> npm redis -v
> > 3.8.3
> >
> > Removi o hredis:
> > C:\Users\Victorugo\Documents\GitHub\naulas\ntalk> npm remove hiredis
> --save
> > C:\Users\Victorugo\Documents\GitHub\naulas\ntalk> npm install
> > C:\Users\Victorugo\Documents\GitHub\naulas\ntalk> npm start
> >
> > O erro persiste.
> >
> > De ultima tentativa instalei um executável desse endereço
> > https://github.com/rgl/redis/downloads
> >
> > Agradeço sua atenção e aguardo help...
> >
> > -
> > You are receiving this because you modified the open/close state.
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/caio-ribeiro-pereira/livro-nodejs/issues/41#issuecomment-215492182
> >
> >
>
> -
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub<
> https://github.com/caio-ribeiro-pereira/livro-nodejs/issues/41#issuecomment-215493108
> >
>
> -
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/caio-ribeiro-pereira/livro-nodejs/issues/41#issuecomment-215495298>
>

-

**Comment by victorhit** [comment]
Quando fui iniciar o mongodb aconteceu o seguinte:


C:\Program Files\MongoDB\Server\3.2\bin>mongo.exe
MongoDB shell version: 3.2.6
connecting to: test
2016-04-28T14:29:58.303-0300 W NETWORK  [thread1] Failed to connect to 127.0.0.1:27017, reason: errno:10061 Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente.
2016-04-28T14:29:58.321-0300 E QUERY    [thread1] Error: couldn't connect to server 127.0.0.1:27017, connection attempt failed :
connect@src/mongo/shell/mongo.js:229:14
@(connect):1:6

exception: connect failed

**Comment by amandaclarck** [comment]
Vitor, vai na pasta onde voce instalou seu mongo e la nessa pasta procura por um arquivo chamado mongod.lock. Deleta ele e tenta conectar o mongo de novo

**Comment by caio-ribeiro-pereira** [comment]
Cara vc ta confundindo as coisas....vamos la

Primeiro lugar, a pasta do redis tem que ser qualquer uma menos na pasta de node_modules, pq o modulo redis do nodejs é apenas um cliente node para se conectar no banco de dados redis (o mesmo serve para o mongodb), entao ao instalar o redis o ideal é instalar naquela pasta de arquivos de programas do windows ou na raíz do hd no C:.

Você acessou redis-server na pasta de modulos do nodejs e é por isso que não reconheceu.
A pasta que você baixou do redis, vai ter dentro os arquivos redis-server.exe, redis-cli.exe, ambos nem precisam abrir o terminal e sim apenas clicar no redis-server.exe para iniciar o servidor, eae vc inicia sua aplicação para se conectar com esse servidor redis.

O mongodb acredito que você instalou certinho, pq ele tem arquivo de setup pra isso.



Regards,
Caio Ribeiro Pereira
Developer, blogger and writter
About: http://crpwebdev.com
Blog: http://udgwebdev.com

**Comment by victorhit** [comment]
Caio agora depois de mudar o lugar da pasta do Redis apareceu o seguinte Erro:

C:\Users\Victorugo\Documents\GitHub\naulas\ntalk> npm start

> ntalk@1.0.0 start C:\Users\Victorugo\Documents\GitHub\naulas\ntalk
> node server

events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Program ENOENT
    at exports._errnoException (util.js:890:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Function.Module.runMain (module.js:449:11)
    at startup (node.js:146:18)
    at node.js:404:3

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE
npm ERR! ntalk@1.0.0 start: `node server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ntalk@1.0.0 start script 'node server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ntalk package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ntalk
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ntalk
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Victorugo\Documents\GitHub\naulas\ntalk\npm-debug.log


O erro ainda está ligado ao Mongo ou Redis?

Agradeço sua atenção e aguardo o help...
