### ISSUE TITLE
Problemas com o mongoose.

### ISSUE THREAD

**Issue by GabrielFeltrin** [caio-ribeiro-pereira/livro-nodejs#43]
Boa noite! 
Sera que você pode me ajudar estou com problemas na hora de criar a base de dados.

![captura de tela de 2016-07-27 19-58-37](https://cloud.githubusercontent.com/assets/20690801/17195533/b733467c-5434-11e6-842b-87dfcb37e08e.png)
![mong](https://cloud.githubusercontent.com/assets/20690801/17195534/b7461180-5434-11e6-8640-7192b1b7eeba.png)

**Comment by caio-ribeiro-pereira** [comment]
Ola qual seria o problema?

Pois mongodb cria a base sozinha conforme vc usa a aplicação.

Regards,
Caio Ribeiro Pereira
https://crpwebdev.com
