### ISSUE TITLE
Erro ao exibir dados do array na tela

### ISSUE THREAD

**Issue by nppneto** [caio-ribeiro-pereira/livro-nodejs#47]
Bom dia, Caio!

A minha dúvida é a seguinte: após efetuar login, cair na página index dos contatos (onde é possível adicionar através de um formulário e consultar os itens adicionados numa tabela abaixo), ao adicionar, recebo o seguinte erro:

[...]
TypeError: C:\Users\Nelson\Documents\Projetos\LivroNodeJS\ntalk\views\contatos\index.ejs:25
    23|                 <% contatos.forEach((contato, index) => { %>

    24|                     <tr>

 >> 25|                         <td><%- contato.nome %></td>

    26|                         <td><%- contato.email %></td>

    27|                         <td>

    28|                             <a href="/contato/<%- index %>">Detalhes</a>

Cannot read property 'nome' of null
    at contatos.forEach (eval at compile (C:\Users\Nelson\Documents\Projetos\LivroNodeJS\ntalk\node_modules\ejs\lib\ejs.js:592:12), <anonymous>:25:25)
    at Array.forEach (<anonymous>)
    at eval (eval at compile
[...]

As Actions responsáveis por essa página seguem abaixo:
--------------------------------------------------------------
        index: function(req, res) {
            const { usuario } = req.session;
            const { contatos } = usuario;
            res.render('contatos/index', { usuario, contatos });
        },
        create: function(req, res) {
            const { contato } = req.body;
            const { usuario } = req.session;
            usuario.contatos.push(contato);
            res.redirect('/contatos');
        }
---------------------------------------------------------------

Fucei de todas as formas e não obtive sucesso... Recorro a você para que eu possa continuar meus estudos.

Um abraço!

**Comment by caio-ribeiro-pereira** [comment]
Olá @nppneto teria como mostrar o código completo desse html? Pois ficou meio confuso de ler e eu gostaria de entender como foi feita o fechamento desse loop de contatos.

**Comment by nppneto** [comment]
Boa noite, Caio!

Segue abaixo o código do arquivo index.ejs

<% include ../layouts/header %>
    <header>
        <h1>Ntalk</h1>
        <h4>Lista de contatos</h4>
    </header>
    <section>
        <form class="form" action="/contato" method="post">
            <input class="form-control" type="text" name="contato[nome]" placeholder="Nome">
            <input class="form-control" type="text" name="contato[email]" placeholder="E-mail">
            <br/>
            <button type="submit">Cadastrar</button>
        </form>

        <table class="table">
            <thead>
                <tr>
                    <th>Nome</th>
                    <th>E-mail</th>
                    <th>Ação</th>
                </tr>
            </thead>
            <tbody>
                <% contatos.forEach((contato, index) => { %>
                    <tr>
                        <td><%- contato.nome %></td>
                        <td><%- contato.email %></td>
                        <td>
                            <a href="/contato/<%- index %>">Detalhes</a>
                        </td>
                    </tr>
                <% }) %>
            </tbody>
        </table>
    </section>
<% include ../layouts/exit %>
<% include ../layouts/footer %>

**Comment by caio-ribeiro-pereira** [comment]
Boa! O código esta ok, poderia me mostrar o arquivo com todas as rotas de contatos?
O bug reporta que contatos esta vindo null e por isso forEach vem bugado, algum bug pode existir na rota, ou caso tudo esteja ok, vc já chegou a reiniciar servidor para forçar que ele limpe o cache? Pois nessa etapa que você esta nem esta sendo usado banco de dados ainda, e algumas mudanças de código no cache do request podem conflitar, de qualquer forma fico no aguardo da rota de contatos, ou se achar melhor, publica no seu github o projeto inteiro e manda o link aqui :)

**Comment by nppneto** [comment]
Ok, Caio... Eu percebi o retorno nulo, porém como estou seguindo o livro e revisei várias vezes, não vi o porque de estar retornando nulo... Vou subir o projeto e te envio!

**Comment by nppneto** [comment]
Caio, segue link do projeto no Git!

https://github.com/nppneto/EstudoLivroNode

Caso veja contato ou usuario fora das { } (sem fazer uso do destructuring), é porque não funcionou e sem o uso dele consegui fazer o sistema rodar até a parte em que te questiono. Estou pesquisando para entender o porquê ainda.

Abraço!

**Comment by caio-ribeiro-pereira** [comment]
@nppneto tenho duas considerações para vc modificar:

1) No app.js mude a linha: `app.use(expressSession({ secret: 'test', resave: true, saveUninitialized: true }));` para `app.use(expressSession({ secret: 'test', resave: false, saveUninitialized: false }));` isso vai garantir que toda vez que reiniciar o server a session será zerada.

2) No `controllers/contatos.js` na action `show` esta invertido `function(res, req)` sendo que a ordem correta desse callback é `function(req, res)`.

De resto seu código esta correto, talvez o problema de `contato null` dentro do `forEach`, seja apenas um dado sujo, que surgiu conforme vc foi codando pelo qual precisa zerar a session para corrigir isso, e do jeito atual ele ta salvando toda session no cookie.

**Comment by nppneto** [comment]
Bom dia, Caio!

Fechou... Estou no trabalho agora. Mais tarde irei testar e te dou o feedback.

Obrigado pela atenção e parabéns pelo livro!

**Comment by caio-ribeiro-pereira** [comment]
tmj amigo, qualquer dúvida, só chamar! :D

**Comment by nppneto** [comment]
Boa noite, Caio!

Como prometido, estou te dando o retorno sobre as alterações que você me passou.
O sistema continua não funcionando. O mesmo erro. Testei em máquinas diferentes para caso de cache só por desencargo de consciência.

Tentarei outras formas para solucionar esse erro. Caso tenha alguma ideia, comente por favor.

Att,

Nelson Neto.

**Comment by caio-ribeiro-pereira** [comment]
Cara, minha sugestão é que você continue seguindo o ebook pois nos próximos capítulos você terá que refactorar muito código, principalmente as sessions, de qualquer forma, vc poderia fazer um print de contatos, antes de fazer um render no seu controller, pra ver o q pode estar gerando de errado.

Achei muito estranho esse bug, pois seu código ta muito parecido com o do livro e aqui não consegui simular o bug, de qualquer forma sugiro seguir o livro para aprender os demais conceitos na prática, e o refactoring vai otimizar e corrigir esse bug de contatos.

**Comment by nppneto** [comment]
Fechou, Caio!

Desculpa tomar seu tempo... Obrigado pelas dicas!

**Comment by caio-ribeiro-pereira** [comment]
Denada amigo! Estou aqui pra ajudar, abs!
