### ISSUE TITLE
Erros no 7.3 e 7.4 || TypeError: db.model is not a function

### ISSUE THREAD

**Issue by tiagoyamamoto** [caio-ribeiro-pereira/livro-nodejs#48]
No 7.3 MONGODB NO NODE.JS UTILIZANDO MONGOOSE a base NTALK não esta sendo criada

![image](https://user-images.githubusercontent.com/8273180/55529270-ecc56580-5676-11e9-91aa-5f0a5c828f0d.png)

Estou tendo dificuldades no 7.4 MODELANDO COM MONGOOSE pode verificar o que está acontecendo?

![image](https://user-images.githubusercontent.com/8273180/55529124-1336d100-5676-11e9-8a6c-113d7be1f87c.png)

![image](https://user-images.githubusercontent.com/8273180/55529139-2e094580-5676-11e9-8a9b-efb19408142b.png)

![image](https://user-images.githubusercontent.com/8273180/55529156-45e0c980-5676-11e9-8ebb-40a20867d25d.png)

**Comment by caio-ribeiro-pereira** [comment]
Olá amigo tudo bem? Você está usando exatamente as mesmas versões do repositório desse livro?

**Comment by tiagoyamamoto** [comment]
![image](https://user-images.githubusercontent.com/8273180/55631255-fe4d6100-578d-11e9-85b8-b7e71a1beb1c.png)

**Comment by tiagoyamamoto** [comment]
![image](https://user-images.githubusercontent.com/8273180/55631281-0efdd700-578e-11e9-8946-93f1347ad86e.png)

**Comment by tiagoyamamoto** [comment]
![image](https://user-images.githubusercontent.com/8273180/55631301-20df7a00-578e-11e9-956f-5f7d8e8cdecf.png)

**Comment by tiagoyamamoto** [comment]
Fiz a instalação de um novo projeto só que ele já instala versões diferentes, como proceder?

![image](https://user-images.githubusercontent.com/8273180/55631786-3b662300-578f-11e9-8903-ede9a7efe831.png)

**Comment by caio-ribeiro-pereira** [comment]
Fala amigo tudo bem?

Veja o package.json desse repositório, copie ele para seu projeto e em
seguida apague a pasta node_modules do seu projeto e por último rode o
comando npm install, que automaticamente ele vai baixar as versões corretas
do package.json que você copiou.

Regards,
Caio Ribeiro Pereira
https://crpwebdev.github.io

**Comment by ibandim123** [comment]
Olá, estou com um problema nessa mesma parte do livro! Ele não reconhece o `return db.model('usuarios', usuario);`

**Comment by caio-ribeiro-pereira** [comment]
@ibandim123 poderia mostrar o print do seu codigo inteiro desse model?

**Comment by ibandim123** [comment]
> @ibandim123 poderia mostrar o print do seu codigo inteiro desse model?

Claro.
![erro](https://user-images.githubusercontent.com/59544620/91764043-fb39e880-ebac-11ea-8b07-566191658f29.jpg)

**Comment by caio-ribeiro-pereira** [comment]
@ibandim123 a variavel db nao foi carregada nesse código, e por isso ela nao existe, provavelmente se vc esta codando e olhando o livro, sugiro que avance algumas páginas do livro com calma, pois o livro vai explicar em páginas futuras como será construido o codigo db.js para carregar nesse model

**Comment by ibandim123** [comment]
Ok, Obg pela atenção!
